site_name: 'Judy Heflin'
site_description: 'The internet home of Judy Heflin'
site_author: 'Judy Heflin'
docs_dir: 'contents'
nav:
- Home:
  - Welcome: 'index.md'
  - About: 'about.md'
- Reading:
  - Resources: 'AIresources2025.md'
- Writing: 
  - Samples: 'writing.md'
extra:
  social:
  - icon: 'fontawesome/brands/linkedin'
    link: 'https://www.linkedin.com/in/judyheflin/'
  - icon: 'fontawesome/brands/github'
    link: 'https://github.com/judyheflin'
  analytics:
    provider: google
    property: G-QNHFVWTDPT
theme:
  name: 'material'
  icon:
    logo: material/cloud
  favicon: images/Vector.png
  features:
  - navigation.tabs
  - navigation.instant
  - navigation.top
  font:
      text: 'DM Mono'
      code: 'Roboto Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
  - 'yaml'
  - 'json'
  - 'bash'
markdown_extensions:
- pymdownx.snippets
- meta
- pymdownx.emoji
- footnotes
- admonition
- pymdownx.details
- pymdownx.superfences
- toc:
    permalink: true
- admonition
- codehilite:
    linenums: False # linenums in codeblock did not play well with numbered list and provided bad experience
plugins:
- search
